# Official WooSignal App Template for WooCommerce

# Label StoreMax
# Version: 6.0.0
# Author: Anthony Gordon
# Homepage: https://woosignal.com
# Documentation: https://woosignal.com/docs/app/label-storemax

### Change App Icon
# 1 Replace: public/assets/icon/appicon.png (1024px1024px icon size)
# 2 Run this command from the terminal: "flutter pub run flutter_launcher_icons:main"

### Uploading the IOS/Android app
# IOS https://flutter.dev/docs/deployment/ios
# Android https://flutter.dev/docs/deployment/android

name: flutter_app
description: Label StoreMax

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  google_fonts: ^2.3.3
  analyzer: ^4.1.0
  intl: ^0.17.0
  page_transition: ^2.0.5
  nylo_framework: ^3.1.3
  woosignal: ^3.1.0
  flutter_stripe: ^3.0.0
  wp_json_api: ^3.1.3
  cached_network_image: ^3.2.1
  package_info: ^2.0.2
  money_formatter: ^0.0.3
  flutter_web_browser: ^0.17.1
  webview_flutter: ^3.0.4
  pull_to_refresh: 2.0.0
  url_launcher: ^6.1.2
  flutter_styled_toast: ^2.1.3
  animate_do: ^2.1.0
  bubble_tab_indicator: ^0.1.5
  status_alert: ^1.0.0
  math_expressions: ^2.3.0
  validated: ^2.0.0
  flutter_spinkit: ^5.1.0
  auto_size_text: ^3.0.0
  html: ^0.15.0
  flutter_widget_from_html: ^0.8.5
  flutter_rating_bar: ^4.0.1
  flutter_staggered_grid_view: ^0.6.1
  flutter_swiper_tv: ^1.1.6-nullsafety
#  firebase_messaging: ^11.2.3
#  firebase_core: ^1.10.5
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.4
  collection: ^1.15.0-nullsafety.4

dev_dependencies:
  flutter_launcher_icons: ^0.9.2
  lints: ^2.0.0
  flutter_test:
    sdk: flutter

# APP ICON
flutter_icons:
  android: true
  ios: true
  image_path: "public/assets/app_icon/appicon.png"
  remove_alpha_ios: true

dependency_overrides:
  intl: ^0.17.0

flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - public/assets/fonts/
    - public/
    - public/assets/json/
    - public/assets/images/
    - lang/
    - .env
