# Official WooSignal App Template for WooCommerce

# Label StoreMax
# Version: 6.15.0
# Author: Anthony Gordon
# Homepage: https://woosignal.com
# Documentation: https://woosignal.com/docs/app/label-storemax

### Change App Icon
# 1 Replace: public/assets/icon/appicon.png (1024px1024px icon size)
# 2 Run this command from the terminal: "dart run flutter_launcher_icons:main"

### Uploading the IOS/Android app
# IOS https://flutter.dev/docs/deployment/ios
# Android https://flutter.dev/docs/deployment/android

name: flutter_app
description: Label StoreMax

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  google_fonts: ^6.2.0
  analyzer: ^5.12.0
  intl: ^0.18.0
  nylo_framework: ^5.21.9
  woosignal: ^3.10.0
  wp_json_api: ^3.3.4
  cached_network_image: ^3.3.1
  package_info_plus: ^4.2.0
  money_formatter: ^0.0.5
  flutter_paypal_payment: ^1.0.6
  flutter_web_browser: ^0.17.1
  pull_to_refresh_flutter3: 2.0.2
  url_launcher: ^6.2.5
  bubble_tab_indicator: ^0.1.5
  status_alert: ^1.0.1
  math_expressions: ^2.4.0
  validated: ^2.0.0
  flutter_spinkit: ^5.1.0
  auto_size_text: ^3.0.0
  html: ^0.15.4
  flutter_widget_from_html_core: ^0.14.11
  flutter_rating_bar: ^4.0.1
  flutter_staggered_grid_view: ^0.7.0
  flutter_swiper_view: ^1.1.8
  firebase_messaging: ^14.7.19
  firebase_core: ^2.27.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.6
  collection: ^1.17.1
  flutter_stripe: ^10.1.1
  razorpay_flutter: ^1.3.6
  animate_do: ^3.3.4

dependency_overrides:
  http: ^1.0.0

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  lints: ^3.0.0
  flutter_test:
    sdk: flutter

# APP ICON
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "public/assets/app_icon/appicon.png"
  remove_alpha_ios: true

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - public/assets/fonts/
    - public/
    - public/assets/json/
    - public/assets/images/
    - lang/
    - .env
